<a href="https://colab.research.google.com/github/pop820469/dt-bootcamp/blob/main/numpypp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(dir(np))

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
help(np.array)

1D array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

wymiar


In [6]:
x.ndim

1

dlug

In [7]:
x.shape

(2,)

In [9]:
print(np.array([1.3, 2.3, 1.4]))

[1.3 2.3 1.4]


2D array

In [11]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [12]:
x.ndim

2

In [13]:
x.size

4

In [14]:
x.shape

(2, 2)

In [16]:
b = np.array([[1, 3, 4], [4, 5, 6]])
b

array([[1, 3, 4],
       [4, 5, 6]])

In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

3D array

In [22]:
x = np.array(
    [[[3, 4, 5],
      [3, 5, 2]],
     [[4, 5, 2],
     [3, 7, 9]]],
)
x

array([[[3, 4, 5],
        [3, 5, 2]],

       [[4, 5, 2],
        [3, 7, 9]]])

In [20]:
x.ndim

3

2 tablice, 2 wiersze, 3 kolumny

In [21]:
x.shape

(2, 2, 3)

In [27]:
a = np.array([3.4, 5.55, 8.6], dtype="int")
a

array([3, 5, 8])

Tworzenie tablic

In [29]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:

np.full(shape=(3, 4), fill_value=5, dtype="int")

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(start=5, stop=35, step=5)

array([ 5, 10, 15, 20, 25, 30])

In [34]:
np.arange(start=500, stop=35, step=-55)

array([500, 445, 390, 335, 280, 225, 170, 115,  60])

In [36]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [37]:
np.linspace(start=3, stop=9, num=4)

array([3., 5., 7., 9.])

In [38]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
a.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])