<a href="https://colab.research.google.com/github/pop820469/dt-bootcamp/blob/main/podst_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print(dir(np))

In [2]:
import numpy as np
np.__version__

'1.26.4'

In [ ]:
help(np.array)

1D array

In [4]:
x = np.array([1, 3])
x

array([1, 3])

wymiar


In [6]:
x.ndim

1

dlug

In [7]:
x.shape

(2,)

In [9]:
print(np.array([1.3, 2.3, 1.4]))

[1.3 2.3 1.4]


2D array

In [11]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [12]:
x.ndim

2

In [13]:
x.size

4

In [14]:
x.shape

(2, 2)

In [16]:
b = np.array([[1, 3, 4], [4, 5, 6]])
b

array([[1, 3, 4],
       [4, 5, 6]])

In [17]:
b.ndim

2

In [18]:
b.shape

(2, 3)

3D array

In [22]:
x = np.array(
    [[[3, 4, 5],
      [3, 5, 2]],
     [[4, 5, 2],
     [3, 7, 9]]],
)
x

array([[[3, 4, 5],
        [3, 5, 2]],

       [[4, 5, 2],
        [3, 7, 9]]])

In [20]:
x.ndim

3

2 tablice, 2 wiersze, 3 kolumny

In [21]:
x.shape

(2, 2, 3)

In [27]:
a = np.array([3.4, 5.55, 8.6], dtype="int")
a

array([3, 5, 8])

Tworzenie tablic

In [29]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [30]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:

np.full(shape=(3, 4), fill_value=5, dtype="int")

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(start=5, stop=35, step=5)

array([ 5, 10, 15, 20, 25, 30])

In [34]:
np.arange(start=500, stop=35, step=-55)

array([500, 445, 390, 335, 280, 225, 170, 115,  60])

In [36]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [37]:
np.linspace(start=3, stop=9, num=4)

array([3., 5., 7., 9.])

In [38]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [39]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [40]:
a.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

operacje na np

In [3]:
a = np.array([3, 1, 4, 2]) #dodaje po kolejnych elementach
b = np.array([3, -1, 3, 2])
print(a)
print(b)

[3 1 4 2]
[ 3 -1  3  2]


In [4]:
a + b

array([6, 0, 7, 4])

In [5]:
a * b

array([ 9, -1, 12,  4])

In [6]:
a / b

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [7]:
a + 3

array([6, 4, 7, 5])

In [8]:
np.add(a, b)

array([6, 0, 7, 4])

In [9]:
np.subtract(a, b)

array([0, 2, 1, 0])

In [10]:
np.multiply(a, b)

array([ 9, -1, 12,  4])

In [11]:
np.divide(a, b)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [12]:
x = np.array([[1, 4], [-2, 0]])
y = np.array([[6, 0], [-1, 2]])
print(x, "\n", y)

[[ 1  4]
 [-2  0]] 
 [[ 6  0]
 [-1  2]]


In [13]:
x * y

array([[6, 0],
       [2, 0]])

In [14]:
np.dot(x, y) #macierz liniowa

array([[  2,   8],
       [-12,   0]])

In [15]:
x.dot(y)

array([[  2,   8],
       [-12,   0]])

In [16]:
y.dot(x)

array([[ 6, 24],
       [-5, -4]])

In [17]:
x @ y #at

array([[  2,   8],
       [-12,   0]])

In [18]:
np.random.seed(0)

In [22]:
np.random.randn(10, 4)

array([[-1.16514984,  0.90082649,  0.46566244, -1.53624369],
       [ 1.48825219,  1.89588918,  1.17877957, -0.17992484],
       [-1.07075262,  1.05445173, -0.40317695,  1.22244507],
       [ 0.20827498,  0.97663904,  0.3563664 ,  0.70657317],
       [ 0.01050002,  1.78587049,  0.12691209,  0.40198936],
       [ 1.8831507 , -1.34775906, -1.270485  ,  0.96939671],
       [-1.17312341,  1.94362119, -0.41361898, -0.74745481],
       [ 1.92294203,  1.48051479,  1.86755896,  0.90604466],
       [-0.86122569,  1.91006495, -0.26800337,  0.8024564 ],
       [ 0.94725197, -0.15501009,  0.61407937,  0.92220667]])

In [23]:
np.random.rand(10, 4) # 0-1

array([[0.10022689, 0.91948261, 0.7142413 , 0.99884701],
       [0.1494483 , 0.86812606, 0.16249293, 0.61555956],
       [0.12381998, 0.84800823, 0.80731896, 0.56910074],
       [0.4071833 , 0.069167  , 0.69742877, 0.45354268],
       [0.7220556 , 0.86638233, 0.97552151, 0.85580334],
       [0.01171408, 0.35997806, 0.72999056, 0.17162968],
       [0.52103661, 0.05433799, 0.19999652, 0.01852179],
       [0.7936977 , 0.22392469, 0.34535168, 0.92808129],
       [0.7044144 , 0.03183893, 0.16469416, 0.6214784 ],
       [0.57722859, 0.23789282, 0.934214  , 0.61396596]])

In [24]:
np.random.randint(10) #1 - 9

3

In [26]:
np.random.randint(low=20, high=40, size=4) # pomiędzy 20 - 39, size= ile

array([37, 21, 38, 37])

In [27]:
np.random.choice([4, 5, 3, 6]) #losowa liczba ze zbioru

5

In [28]:
np.random.choice(["java", "python", "js"]) #lub ze zbioru

'java'

In [30]:
dta = np.arange(10)
dta

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
np.random.shuffle(dta) #nie tworzy kopi

In [32]:
dta

array([0, 7, 1, 3, 9, 6, 4, 8, 5, 2])

In [33]:
np.exp(1) #stała eulera

2.718281828459045

In [34]:
np.sqrt(8)

2.8284271247461903

In [35]:
np.all([2, 5, 8]) #wszystkie True

True

In [36]:
np.any([8, 9, 6]) #przynajmniej jedna

True

In [38]:
a = np.random.rand(5)
a

array([0.61765792, 0.54249878, 0.85461358, 0.74383455, 0.47859633])

In [39]:
np.argmax(a) # index max

2

In [40]:
np.argmin(a) # index min

4

In [41]:
np.argsort(a) # -->

array([4, 1, 0, 3, 2])

In [42]:
np.max(a)

0.8546135803107144

In [43]:
np.min(a)

0.4785963256187501

In [44]:
np.mean(a)

0.6474402284691061

In [45]:
np.median(a) # odchylenie

0.6176579160958802

In [46]:
np.std(a) # odch. standardowe

0.13610335803831713

In [47]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

a[ind], a[start:stop], a[:stop], a[start:]

In [48]:
a[4]

4

In [49]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [50]:
a[[0, 4]] # wycinanie kilku

array([0, 4])

In [52]:
a = a.reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [53]:
a[3]

array([15, 16, 17, 18, 19])

In [54]:
a[:, 0]

array([ 0,  5, 10, 15])

In [55]:
a[1, 1]

6

In [56]:
a[3, 1]

16

In [57]:
a[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [59]:
a[1, 2] = 14 # zamiana

In [60]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

iteracje po tablicach

In [61]:
for row in a:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [62]:
for row in a:
  print(row[3])

3
8
13
18


In [64]:
for item in a.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


zmiana rozm tablic

In [65]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
a.shape

(4, 5)

In [67]:
a.reshape(5 ,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [68]:
a.ravel() # spłaszczenie

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [72]:
a.T # zamienia kol z wiersz

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

maski logiczne

In [75]:
a = np.arange(start=-10, stop=10, step=0.5)
a = a.reshape(10, -1)
a # żeby wyświetlić

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [76]:
a > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [77]:
a[a>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [78]:
np.bitwise_and(a > -5, a < 5) # val and val nie działa; bitwise_or

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
fgs